/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerResponse { 
    /**
     * Payment Provider\'s identifier for the customer.
     */
    paymentProviderId: string;
    /**
     * Customer\'s full name or company name
     */
    name: string;
    /**
     * Customer\'s email address
     */
    email: string;
    /**
     * Setup Intent ID
     */
    clientSecret: string;
}

