/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payment method if payment has been attempted, null otherwise
 */
export interface PaymentTransactionResponsePaymentMethod { 
    /**
     * Payment Method ID.
     */
    paymentMethodId: string;
    /**
     * Payment provider ID associated with this payment method.
     */
    paymentProviderId: string;
    /**
     * Last four digits of payment method.
     */
    lastFourDigits: number;
    /**
     * Expiry month.
     */
    expiryMonth: number;
    /**
     * Expiry year.
     */
    expiryYear: number;
    /**
     * Brand
     */
    brand: PaymentTransactionResponsePaymentMethod.BrandEnum | null;
    /**
     * Type of the card/payment method
     */
    type: PaymentTransactionResponsePaymentMethod.TypeEnum | null;
    /**
     * Account ID.
     */
    accountId: string;
    /**
     * Payment provider ID associated with this accountId.
     */
    customerPaymentProviderId: string;
    /**
     * Org ID.
     */
    orgId: string;
    /**
     * Whether or not this payment method is default for the customer.
     */
    isDefault: boolean;
}
export namespace PaymentTransactionResponsePaymentMethod {
    export type BrandEnum = 'American Express' | 'Diners Club' | 'Discover' | 'Eftpos Australia' | 'JCB' | 'MasterCard' | 'UnionPay' | 'Visa' | 'Unknown';
    export const BrandEnum = {
        AmericanExpress: 'American Express' as BrandEnum,
        DinersClub: 'Diners Club' as BrandEnum,
        Discover: 'Discover' as BrandEnum,
        EftposAustralia: 'Eftpos Australia' as BrandEnum,
        Jcb: 'JCB' as BrandEnum,
        MasterCard: 'MasterCard' as BrandEnum,
        UnionPay: 'UnionPay' as BrandEnum,
        Visa: 'Visa' as BrandEnum,
        Unknown: 'Unknown' as BrandEnum
    };
    export type TypeEnum = 'credit' | 'debit' | 'prepaid' | 'unknown';
    export const TypeEnum = {
        Credit: 'credit' as TypeEnum,
        Debit: 'debit' as TypeEnum,
        Prepaid: 'prepaid' as TypeEnum,
        Unknown: 'unknown' as TypeEnum
    };
}


