/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PaymentTransactionTypeEnum = 'credit_card' | 'cash' | 'check';

export const PaymentTransactionTypeEnum = {
    CreditCard: 'credit_card' as PaymentTransactionTypeEnum,
    Cash: 'cash' as PaymentTransactionTypeEnum,
    Check: 'check' as PaymentTransactionTypeEnum
};

