/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentTransactionStatus } from './paymentTransactionStatus';
import { PaymentTransactionResponsePaymentMethod } from './paymentTransactionResponsePaymentMethod';


export interface PaymentTransactionResponse { 
    /**
     * Payment Transaction ID.
     */
    paymentTransactionId: string;
    /**
     * The identifier of the payment intent associated with the payment transaction.
     */
    paymentProviderId: string;
    /**
     * Account id.
     */
    accountId: string;
    /**
     * Account Name
     */
    accountName: string;
    /**
     * Account Email Address
     */
    email: string | null;
    /**
     * Account Mobile Number
     */
    mobileNumber: string;
    /**
     * Site id.
     */
    siteId: string;
    /**
     * Shopping cart id.
     */
    cartId: string | null;
    /**
     * Amount in smallest currency unit (e.g. cents for USD).
     */
    amount: number;
    paymentTransactionStatus: PaymentTransactionStatus;
    paymentMethod: PaymentTransactionResponsePaymentMethod | null;
    /**
     * Client secret for use with payment provider.
     */
    clientSecret: string | null;
    /**
     * Created at.
     */
    createdAt: string;
    /**
     * Created at.
     */
    updatedAt: string | null;
}
export namespace PaymentTransactionResponse {
}


