/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TransactionStatusCodeNames = 'IN_PROGRESS' | 'SUCCESS' | 'FAILED' | 'INCOMPLETE';

export const TransactionStatusCodeNames = {
    InProgress: 'IN_PROGRESS' as TransactionStatusCodeNames,
    Success: 'SUCCESS' as TransactionStatusCodeNames,
    Failed: 'FAILED' as TransactionStatusCodeNames,
    Incomplete: 'INCOMPLETE' as TransactionStatusCodeNames
};

