/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TransactionTypeEnum = 'charge' | 'refund';

export const TransactionTypeEnum = {
    Charge: 'charge' as TransactionTypeEnum,
    Refund: 'refund' as TransactionTypeEnum
};

